<a href="https://colab.research.google.com/github/adnanfathoni88/numerical_methods/blob/main/UTS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**JAWABAN UTS** <br>
Nama : Adnan Fathoni <br>
Kelas : IF10 <br>
NIM : 24.21.1591 <br>

LINK:
https://colab.research.google.com/drive/14gZ9dCOXXn-Ax1wSIUCIoyjW-4KUFkgP?usp=sharing


#1

Manfaat metode numerik dalam bidang sains dan teknik antara lain:


1.   Memecahkan persamaan matematika yang tidak dapat diselesaikan secara analitis.
2.       Menganalisis masalah yang kompleks dengan model matematika.
3. Meningkatkan akurasi dan efisiensi perhitungan dalam simulasi dan eksperimen.
4. Membantu optimasi desain dalam rekayasa teknik
5. Menyediakan solusi untuk masalah yang melibatkan data besar atau variabel yang sangat kompleks.

#2

a. Bentuk Persamaan

x + y + z = 150 <br>
        y = 2z <br>
        x = z + 30

b. LU

In [ ]:
import numpy as np

def lu_decomposition(A):
    n = A.shape[0]
    L = np.zeros_like(A, dtype=np.float64)
    U = np.zeros_like(A, dtype=np.float64)

    for i in range(n):
        # Mengisi elemen U
        for k in range(i, n):
            U[i, k] = A[i, k] - sum(L[i, j] * U[j, k] for j in range(i))

        # Mengisi elemen L
        for k in range(i, n):
            if k == i:
                L[i, i] = 1  # Elemen diagonal L harus 1
            else:
                L[k, i] = (A[k, i] - sum(L[k, j] * U[j, i] for j in range(i))) / U[i, i]

    return L, U

def forward_substitution(L, b):
    """Menyelesaikan Ly = b (proses substitusi maju)"""
    n = L.shape[0]
    y = np.zeros_like(b, dtype=np.float64)

    for i in range(n):
        y[i] = (b[i] - sum(L[i, j] * y[j] for j in range(i))) / L[i, i]

    return y

def backward_substitution(U, y):
    """Menyelesaikan Ux = y (proses substitusi mundur)"""
    n = U.shape[0]
    x = np.zeros_like(y, dtype=np.float64)

    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - sum(U[i, j] * x[j] for j in range(i + 1, n))) / U[i, i]

    return x

def lu_solve(A, b):
    """Menyelesaikan sistem persamaan Ax = b menggunakan dekomposisi LU"""
    L, U = lu_decomposition(A)
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    return x

# fungsi cetak u
def u_print():
  print("Matriks U:")
  print(U)

# fungsi cetak l
def l_print():
  print("Matriks L:")
  print(L)

# Contoh
A = np.array([[1, 1, 1],
              [0, 1, -2],
              [1, 0, -1]], dtype=np.float64)

b = np.array([150, 0, 30], dtype=np.float64)

# Menyelesaikan Ax = b
x = lu_solve(A, b)
print("Solusi dari sistem persamaan:")
print(x)

L, U = lu_decomposition(A)
print("")
u_print()
print("")
l_print()

Solusi dari sistem persamaan:
[60. 60. 30.]

Matriks U:
[[ 1.  1.  1.]
 [ 0.  1. -2.]
 [ 0.  0. -4.]]

Matriks L:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 1. -1.  1.]]


Jadi Komputer dekstop 60 unit, laptop 60 unit, tablet 30 unit

#3

gauss Jacobi

In [ ]:
# 4x + y + z = 6
# x + 4y + z = 8
# x + y + 4z = 6

f1 = lambda x, y, z: (6 - y - z) / 4
f2 = lambda x, y, z: (8 -x - z) / 4
f3 = lambda x, y, z: (6 - x - y) / 4

# Inisialisasi nilai awal
x0 = 0
y0 = 0
z0 = 0
count = 1
# input
e = float(input('Enter tolerable error: '))
# Print header
print('\nCount\tx\ty\tz\n')
condition = True
while condition:
    x1 = f1(x0,y0,z0)
    y1 = f2(x0,y0,z0)
    z1 = f3(x0,y0,z0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
    e1 = abs(x0-x1);
    e2 = abs(y0-y1);
    e3 = abs(z0-z1);

    #update nilai
    count += 1
    x0 = x1
    y0 = y1
    z0 = z1
    condition = e1>e and e2>e and e3>e
print('\nSolution: x=%0.3f, y=%0.3f and z = %0.3f\n'% (x1,y1,z1))

Enter tolerable error: 0.001

Count	x	y	z

1	1.5000	2.0000	1.5000

2	0.6250	1.2500	0.6250

3	1.0312	1.6875	1.0312

4	0.8203	1.4844	0.8203

5	0.9238	1.5898	0.9238

6	0.8716	1.5381	0.8716

7	0.8976	1.5642	0.8976

8	0.8846	1.5512	0.8846

9	0.8911	1.5577	0.8911

10	0.8878	1.5545	0.8878

11	0.8894	1.5561	0.8894

12	0.8886	1.5553	0.8886


Solution: x=0.889, y=1.555 and z = 0.889



#4

a. Biseksi

In [ ]:
# fungsi x
def f(x):
    # x3 + 2x2 – 2x + 2
    return (x*x*x)+(2*x*x)-(2*x)+2

# metode biseksi
def bisection(x0, x1, e):
  step = 1
  print('\n\n*** METODE BISEKSI ***')
  condition = True
  while condition:

    # rumus biseksi
    x2 = (x0 + x1) / 2
    print('Iterasi-%d, x2 = %0.6f dan f(x2) = %0.6f' % (step, x2, f(x2)))

    if (f(x0) * f(x2) < 0):
      x1 = x2
    else:
      x0 = x2

    step = step + 1
    condition = abs(f(x2)) > e

  print('\nNilai akar: %0.8f' % x2)

# input nilai tebakan dan toleransi error
x0 = input('x0: ')
x1 = input('x1: ')
e = input('Toleransi Error: ')

# konversii input (string -> float)
x0 = float(x0)
x1 = float(x1)
e = float(e)

# cek nilai tebakan apakah masuk di PNL
if (f(x0) * f(x1) > 0.0):
  print('Nilai tebakan salah')
  print('Silahkan mencoba lagi')
else:
  bisection(x0, x1, e)

x0: -3
x1: -2
Toleransi Error: 0.05


*** METODE BISEKSI ***
Iterasi-1, x2 = -2.500000 dan f(x2) = 3.875000
Iterasi-2, x2 = -2.750000 dan f(x2) = 1.828125
Iterasi-3, x2 = -2.875000 dan f(x2) = 0.517578
Iterasi-4, x2 = -2.937500 dan f(x2) = -0.214600
Iterasi-5, x2 = -2.906250 dan f(x2) = 0.158051
Iterasi-6, x2 = -2.921875 dan f(x2) = -0.026623

Nilai akar: -2.92187500


b. Regula Falsi

In [ ]:
# x3 + 2x2 – 2x + 2 =0

def f(x):
    return x**3 + 2*x**2 - 2*x + 2

def regula_falsi(x0, x1, e):
  step = 1
  print('\n\n*** METODE REGULA FALSI ***')
  condition = True
  while condition:
    x2 = x0 - (x1-x0) * f(x0) / (f(x1) - f(x0))
    print('Iterasi-%d, x2 = %0.6f dan f(x2) = %0.6f' % (step, x2, f(x2)))

    if (f(x0) * f(x2) < 0):
      x1 = x2
    else:
      x0 = x2

    step = step + 1
    condition = abs(f(x2)) > e

  print('\nNilai akar: %0.8f' % x2)

# input nilai tebakan dan toleransi error
x0 = input('x0: ')
x1 = input('x1: ')
e = input('Toleransi Error: ')

# konversii input (string -> float)
x0 = float(x0)
x1 = float(x1)
e = float(e)

# cek nilai tebakan apakah masuk di PNL
if (f(x0) * f(x1) > 0.0):
  print('Nilai tebakan salah')
  print('Silahkan mencoba lagi')
else:
  regula_falsi(x0, x1, e)

x0: -3
x1: -2
Toleransi Error: 0.05


*** METODE REGULA FALSI ***
Iterasi-1, x2 = -2.857143 dan f(x2) = 0.717201
Iterasi-2, x2 = -2.916808 dan f(x2) = 0.033624

Nilai akar: -2.91680815
